using Array;
using Array.Latihan;

//Declaration.declarationArrayToInt();
//Declaration.declarationArrayToChar();
//Lat_1.printOddNumber();
//Lat_2.sortingElemenArray();
//Multidimensional.printArrayDuaDimensi();
//Lat_3.printDiagonalSame();
//JaggedArray.jaggedArrayBasic();
//Lat_4.palindromeBasic();
//Lat_5.printJaggedArray();
//Lat_6.sumArrayMultidimensi();
//Length_Rank_Property.printEmployee();
//Length_Rank_Property.printStudents();
//Length_Rank_Property.printNumbers();
//ParameterMethods.main();
//ForEach.main();
//ArrayObject.displayArrayOfObject();
//Lat_7.printStudents();
Lat_8.printDosen();